environments:
  - WindFarmControl:
      expected_reward: 0.0
      description: <description-of-the-environment>
      linux_url: "[ANONYMIZED]"
      darwin_url: ""
      win_url: "[ANONYMIZED]"
  - WildfireResourceManagement:
      expected_reward: 0.0
      description: <description-of-the-environment>
      linux_url: "[ANONYMIZED]"
      darwin_url: ""
      win_url: "[ANONYMIZED]"
  - DroneBasedReforestation:
      expected_reward: 0.0
      description: <description-of-the-environment>
      linux_url: "[ANONYMIZED]"
      darwin_url: ""
      win_url: "[ANONYMIZED]"
  - OceanPlasticCollector:
      expected_reward: 0.0
      description: <description-of-the-environment>
      linux_url: "[ANONYMIZED]"
      darwin_url: ""
      win_url: "[ANONYMIZED]"
  - AerialWildfireSuppression:
      expected_reward: 0.0
      description: ""
      linux_url: "[ANONYMIZED]"
      darwin_url: ""
      win_url: "[ANONYMIZED]"
